/*
=======================================
Exploratory Magnitude
=======================================
	Mengcompare nilai measure by categori
	untk membantu memahami pentingnya perbedaan categori
==========================================================
*/

-- task --
-- 1. find the total customer by country 
-- 2. find total customer by gender
-- 3. find total products by category
-- 4. what is the average costs in each category
-- 5. what is the total revenue generated for each category?
-- 6. find total revenue is generated by each customer
-- 7. what is the distribution of sold items across countries ?

-- 1 total customer by country
SELECT 
	country,
	COUNT(DISTINCT customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers;

-- 2. total customers by gender
SELECT 
	gender,
	COUNT(DISTINCT customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- 3. total products by category
SELECT
	category,
	COUNT(DISTINCT product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products desc;

-- 4. average cost in each category
SELECT
	category,
	AVG(cost) average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;

--5. total revenue generated for each category
SELECT	
	dp.category,
	SUM(fs.sales_amount) total_sales
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dp
ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_sales DESC;

-- total revenue generated by each customer
SELECT
	dc.customer_id,
	dc.first_name + ' '+ dc.last_name AS customer_name,
	SUM(fs.sales_amount) total_sales
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_id, dc.first_name + ' '+ dc.last_name
ORDER BY total_sales DESC;

-- what is the distribution of sold items across countries
SELECT 
	dc.country,
	SUM(fs.quantity) total_sold
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.product_key = dc.customer_key
GROUP BY country
ORDER BY total_sold DESC;